### ISSUE TITLE
Dependent pods should restart when SealedSecret resources are modified.

### ISSUE THREAD

**Issue by Stephen-ONeil** [PHACDataHub/cpho-phase2#159]
Updated one of our SealedSecret-stored app config values, had to manually restart the app pod to get the new value in to its env vars. Not at all ideal, should be automatic, with rolling updates to avoid down time and all that nice-ness.

**Comment by Stephen-ONeil** [comment]
Update: or perhaps it would have if the secret was _actually_ successfully synced, as the flux status notifications claimed
![image](https://github.com/PHACDataHub/cpho-phase2/assets/11301919/5ebcd81a-7ef3-4cc3-9718-372ae8147c79)

**Comment by Stephen-ONeil** [comment]
Fixed the above update, unrelated bug, the application pod still required a restart in the end.

**Comment by vedantthapa** [comment]
I believe this is more of a [kubernetes thing](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data) rather than a SealedSecret issue -
> If a container already consumes a Secret in an environment variable, a Secret update will not be seen by the container unless it is restarted. There are third party solutions for triggering restarts when secrets change.

That is to say, it'd still exist when we migrate to SOPS unless we use a third-party solution like https://github.com/stakater/Reloader. However, that implies more pods.
